# General config
safe: false
markdown: kramdown

# Overall site config 
name: "TEDxUofW"
url: "http://tedxuofw.com"

# Plugins 
gems: [jekyll-assets]

# Plugin: jekyll-assets
assets:
    cache: true
    cachebust: hard
    sources:
        - _assets/fonts
        - _assets/javascripts
        - _assets/media
        - _assets/stylesheets
        - _assets/vendors/fancybox2
    gzip: [ text/css, application/javascript ]